# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-21 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_ip', models.CharField(max_length=100, verbose_name='\u516c\u7f51IP')),
                ('intranet_ip', models.CharField(max_length=100, verbose_name='\u5185\u7f51IP')),
                ('host_name', models.CharField(max_length=50, verbose_name='\u4e3b\u673a\u540d')),
                ('os', models.CharField(max_length=50, verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
                ('cpu_model', models.CharField(max_length=100, verbose_name='CPU\u578b\u53f7')),
                ('cpu_thread_number', models.PositiveIntegerField(verbose_name='CPU\u7ebf\u7a0b\u6570')),
                ('memory', models.CharField(max_length=50, verbose_name='\u5185\u5b58')),
                ('disk', models.TextField(verbose_name='\u78c1\u76d8')),
                ('minion_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'asset_info',
            },
        ),
        migrations.CreateModel(
            name='Charts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_time', models.CharField(max_length=50)),
                ('pv_number', models.IntegerField()),
                ('uv_number', models.IntegerField()),
            ],
            options={
                'db_table': 'web_access_count',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='\u7528\u6237\u540d')),
                ('passwd', models.CharField(max_length=255, verbose_name='\u5bc6\u7801')),
                ('email', models.EmailField(max_length=150)),
                ('register_time', models.DateTimeField(null=True, verbose_name='\u6ce8\u518c\u65f6\u95f4')),
                ('last_login_time', models.DateTimeField(null=True, verbose_name='\u6700\u540e\u767b\u5f55\u65f6\u95f4')),
                ('last_login_ip', models.GenericIPAddressField(null=True, verbose_name='\u6700\u540e\u767b\u5f55IP')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
