# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-28 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinfo',
            name='minion_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
